### ISSUE TITLE
Build error on UE 4.15

### ISSUE THREAD

**Issue by elliotlo** [VSZue/DonAINavigation#2]
When I upgrade to 4.15. THere are some error when built:

```
1>f:\project\plugins\donainavigation\source\donainavigation\classes\DonNavigationCommon.h(49): error C2065: 'FILETIME': undeclared identifier
1>f:\project\plugins\donainavigation\source\donainavigation\classes\DonNavigationCommon.h(49): error C2146: syntax error: missing ';' before identifier 'ft'
1>f:\project\plugins\donainavigation\source\donainavigation\classes\DonNavigationCommon.h(49): error C2065: 'ft': undeclared identifier
1>f:\project\plugins\donainavigation\source\donainavigation\classes\DonNavigationCommon.h(50): error C2065: 'LARGE_INTEGER': undeclared identifier
1>f:\project\plugins\donainavigation\source\donainavigation\classes\DonNavigationCommon.h(50): error C2146: syntax error: missing ';' before identifier 'li'
1>f:\project\plugins\donainavigation\source\donainavigation\classes\DonNavigationCommon.h(50): error C2065: 'li': undeclared identifier
1>f:\project\plugins\donainavigation\source\donainavigation\classes\DonNavigationCommon.h(54): error C2065: 'ft': undeclared identifier
1>f:\project\plugins\donainavigation\source\donainavigation\classes\DonNavigationCommon.h(54): error C3861: 'GetSystemTimeAsFileTime': identifier not found
1>f:\project\plugins\donainavigation\source\donainavigation\classes\DonNavigationCommon.h(55): error C2065: 'li': undeclared identifier
1>f:\project\plugins\donainavigation\source\donainavigation\classes\DonNavigationCommon.h(55): error C2228: left of '.LowPart' must have class/struct/union
1>  f:\project\plugins\donainavigation\source\donainavigation\classes\DonNavigationCommon.h(55): note: type is 'unknown-type'
1>f:\project\plugins\donainavigation\source\donainavigation\classes\DonNavigationCommon.h(55): error C2065: 'ft': undeclared identifier
1>f:\project\plugins\donainavigation\source\donainavigation\classes\DonNavigationCommon.h(55): error C2228: left of '.dwLowDateTime' must have class/struct/union
1>  f:\project\plugins\donainavigation\source\donainavigation\classes\DonNavigationCommon.h(55): note: type is 'unknown-type'
1>f:\project\plugins\donainavigation\source\donainavigation\classes\DonNavigationCommon.h(56): error C2065: 'li': undeclared identifier
1>f:\project\plugins\donainavigation\source\donainavigation\classes\DonNavigationCommon.h(56): error C2228: left of '.HighPart' must have class/struct/union
1>  f:\project\plugins\donainavigation\source\donainavigation\classes\DonNavigationCommon.h(56): note: type is 'unknown-type'
1>f:\project\plugins\donainavigation\source\donainavigation\classes\DonNavigationCommon.h(56): error C2065: 'ft': undeclared identifier
1>f:\project\plugins\donainavigation\source\donainavigation\classes\DonNavigationCommon.h(56): error C2228: left of '.dwHighDateTime' must have class/struct/union
1>  f:\project\plugins\donainavigation\source\donainavigation\classes\DonNavigationCommon.h(56): note: type is 'unknown-type'
1>f:\project\plugins\donainavigation\source\donainavigation\classes\DonNavigationCommon.h(58): error C2065: 'li': undeclared identifier
1>f:\project\plugins\donainavigation\source\donainavigation\classes\DonNavigationCommon.h(58): error C2228: left of '.QuadPart' must have class/struct/union
1>  f:\project\plugins\donainavigation\source\donainavigation\classes\DonNavigationCommon.h(58): note: type is 'unknown-type'
1>f:\project\plugins\donainavigation\source\donainavigation\classes\DonNavigationCommon.h(49): error C2065: 'FILETIME': undeclared identifier
1>f:\project\plugins\donainavigation\source\donainavigation\classes\DonNavigationCommon.h(49): error C2146: syntax error: missing ';' before identifier 'ft'
1>f:\project\plugins\donainavigation\source\donainavigation\classes\DonNavigationCommon.h(49): error C2065: 'ft': undeclared identifier
1>f:\project\plugins\donainavigation\source\donainavigation\classes\DonNavigationCommon.h(50): error C2065: 'LARGE_INTEGER': undeclared identifier
1>f:\project\plugins\donainavigation\source\donainavigation\classes\DonNavigationCommon.h(50): error C2146: syntax error: missing ';' before identifier 'li'
1>f:\project\plugins\donainavigation\source\donainavigation\classes\DonNavigationCommon.h(50): error C2065: 'li': undeclared identifier
1>f:\project\plugins\donainavigation\source\donainavigation\classes\DonNavigationCommon.h(54): error C2065: 'ft': undeclared identifier
1>f:\project\plugins\donainavigation\source\donainavigation\classes\DonNavigationCommon.h(54): error C3861: 'GetSystemTimeAsFileTime': identifier not found
1>f:\project\plugins\donainavigation\source\donainavigation\classes\DonNavigationCommon.h(55): error C2065: 'li': undeclared identifier
1>f:\project\plugins\donainavigation\source\donainavigation\classes\DonNavigationCommon.h(55): error C2228: left of '.LowPart' must have class/struct/union
1>  f:\project\plugins\donainavigation\source\donainavigation\classes\DonNavigationCommon.h(55): note: type is 'unknown-type'
1>f:\project\plugins\donainavigation\source\donainavigation\classes\DonNavigationCommon.h(55): error C2065: 'ft': undeclared identifier
1>f:\project\plugins\donainavigation\source\donainavigation\classes\DonNavigationCommon.h(55): error C2228: left of '.dwLowDateTime' must have class/struct/union
1>  f:\project\plugins\donainavigation\source\donainavigation\classes\DonNavigationCommon.h(55): note: type is 'unknown-type'
1>f:\project\plugins\donainavigation\source\donainavigation\classes\DonNavigationCommon.h(56): error C2065: 'li': undeclared identifier
1>f:\project\plugins\donainavigation\source\donainavigation\classes\DonNavigationCommon.h(56): error C2228: left of '.HighPart' must have class/struct/union
1>  f:\project\plugins\donainavigation\source\donainavigation\classes\DonNavigationCommon.h(56): note: type is 'unknown-type'
1>f:\project\plugins\donainavigation\source\donainavigation\classes\DonNavigationCommon.h(56): error C2065: 'ft': undeclared identifier
1>f:\project\plugins\donainavigation\source\donainavigation\classes\DonNavigationCommon.h(56): error C2228: left of '.dwHighDateTime' must have class/struct/union
1>  f:\project\plugins\donainavigation\source\donainavigation\classes\DonNavigationCommon.h(56): note: type is 'unknown-type'
1>f:\project\plugins\donainavigation\source\donainavigation\classes\DonNavigationCommon.h(58): error C2065: 'li': undeclared identifier
1>f:\project\plugins\donainavigation\source\donainavigation\classes\DonNavigationCommon.h(58): error C2228: left of '.QuadPart' must have class/struct/union
1>  f:\project\plugins\donainavigation\source\donainavigation\classes\DonNavigationCommon.h(58): note: type is 'unknown-type'
```

```
1>f:\project\Plugins\DonAINavigation\Source\DonAINavigation\Private\Legacy\DEPRECATED_VolumeAdaptiveBuilder.cpp(253): error C2039: 'ComponentOverlapComponents_NEW': is not a member of 'UKismetSystemLibrary'
1>  C:\Program Files\Epic Games\UE_4.15\Engine\Source\Runtime\Engine\Classes\Kismet/KismetSystemLibrary.h(76): note: see declaration of 'UKismetSystemLibrary'
1>f:\project\Plugins\DonAINavigation\Source\DonAINavigation\Private\Legacy\DEPRECATED_VolumeAdaptiveBuilder.cpp(253): error C3861: 'ComponentOverlapComponents_NEW': identifier not found
1>f:\project\Plugins\DonAINavigation\Source\DonAINavigation\Private\Legacy\DEPRECATED_VolumeAdaptiveBuilder.cpp(276): error C2039: 'ComponentOverlapComponents_NEW': is not a member of 'UKismetSystemLibrary'
1>  C:\Program Files\Epic Games\UE_4.15\Engine\Source\Runtime\Engine\Classes\Kismet/KismetSystemLibrary.h(76): note: see declaration of 'UKismetSystemLibrary'
1>f:\project\Plugins\DonAINavigation\Source\DonAINavigation\Private\Legacy\DEPRECATED_VolumeAdaptiveBuilder.cpp(276): error C3861: 'ComponentOverlapComponents_NEW': identifier not found
1>f:\project\Plugins\DonAINavigation\Source\DonAINavigation\Private\Legacy\DEPRECATED_VolumeAdaptiveBuilder.cpp(421): error C2039: 'ComponentOverlapComponents_NEW': is not a member of 'UKismetSystemLibrary'
1>  C:\Program Files\Epic Games\UE_4.15\Engine\Source\Runtime\Engine\Classes\Kismet/KismetSystemLibrary.h(76): note: see declaration of 'UKismetSystemLibrary'
1>f:\project\Plugins\DonAINavigation\Source\DonAINavigation\Private\Legacy\DEPRECATED_VolumeAdaptiveBuilder.cpp(421): error C3861: 'ComponentOverlapComponents_NEW': identifier not found
1>f:\project\Plugins\DonAINavigation\Source\DonAINavigation\Private\Legacy\DEPRECATED_VolumeAdaptiveBuilder.cpp(1116): error C2039: 'ComponentOverlapComponents_NEW': is not a member of 'UKismetSystemLibrary'
1>  C:\Program Files\Epic Games\UE_4.15\Engine\Source\Runtime\Engine\Classes\Kismet/KismetSystemLibrary.h(76): note: see declaration of 'UKismetSystemLibrary'
1>f:\project\Plugins\DonAINavigation\Source\DonAINavigation\Private\Legacy\DEPRECATED_VolumeAdaptiveBuilder.cpp(1116): error C3861: 'ComponentOverlapComponents_NEW': identifier not found
```

**Comment by VSZue** [comment]
4.15 Plugin binaries are available at http://www.drunkonnectar.com/3d-pathfinding-ue4/

Github source will be updated whenever I find some free time :)

**Comment by elliotlo** [comment]
Thank you!
